context: kops.peelmicro.com   # kube-context (--kube-context)
 
releases:
  # Published chart example
  - name: jenkins-course-udemy    # name of this release
    namespace: default            # target namespace
    chart: stable/jenkins         # repository/chart` syntax
    values:
      - jenkins/jenkins_custom_values.yaml   # value files (--values)
    set:                                   # values (--set)
      - name: Master.ServiceType
        value: NodePort
      - name: Master.NodePort
        value: 30477
      - name: Persistence.Size
        value: 2Gi
      - name: Master.AdminPassword
        value: <some_password>
      - name: rbac.install
        value: true
